#Цей код представляє конфігурацію Kubernetes Service для розгортання мікросервісу збору книг ("bookcollection")

apiVersion: v1 #Це поле вказує на використання API версії 1 для конфігурації Kubernetes.
kind: Service # Вказує тип ресурсу, який ми визначаємо
metadata: #В цьому розділі ми вказуємо метадані (ім'я) для цього об'єкта.
  name: book-srv #Це ім'я служби
spec: # Цей розділ містить специфікацію конфігурації для служби.
  type: NodePort # Вказує тип служби
  selector: #Вказує, які ресурси в кластері слід підключати до цієї служби
    app: bookcollection #це ресурси з міткою
  ports: # Вказує порти, які служба повинна слухати.
    - name: bookcollection #Це ім'я для порту.
      protocol: TCP #Вказує протокол (TCP) для цього порту.
      port: 80 #Зазначає порт на вузлі, на якому служба буде доступна.
      targetPort: 80 #Зазначає порт, на який буде перенаправлено трафік внутрішнього кластера