#Цей код представляє конфігурацію Kubernetes для розгортання (Deployment) 
#та служби (Service) для додатку під назвою "bookbyte"

apiVersion: apps/v1 #Версія API для використання (v1 версія API для роботи з ресурсами Deployment).
kind: Deployment # Вказує тип ресурсу, який ми визначаємо
metadata: #Метадані ресурсу, такі як назва розгортання
  name: bookbyte-depl
spec: #Специфікація ресурсу, де вказується кількість реплік (replicas), селектор для вибору потрібних об'єктів та конфігурація контейнера.
  replicas: 1 #Кількість реплік (під'єднаних екземплярів) додатку - в даному випадку, 1.
  selector: #Селектор, за яким об'єкти Deployment визначають, які Pod'и належать до цього розгортання.
    matchLabels:
      app: bookbyte
  template: #Шаблон для конфігурації Pod'а.
    metadata: #Метадані для Pod'а.
      labels: #Мітки, які визначають, до якого розгортання вони належать.
        app: bookbyte
    spec: #Специфікація самого Pod'а.
      containers: #Опис контейнера, який має бути запущений в Pod'і.
      - name: bookbyte #Назва контейнера ("bookbyte").
        image: dipas/bookbyte:latest #Docker-образ, який буде використовуватися для цього контейнера.
        ports: # Порти, які відкриваються у контейнері.
        - containerPort: 80

---
apiVersion: v1 # Версія API для використання (v1 версія API для роботи з ресурсами Service).
kind: Service # Вказує тип ресурсу, який ми визначаємо
metadata: # Метадані ресурсу, такі як назва служби (bookbyte-clusterip-srv).
  name: bookbyte-clusterip-srv
spec: #Специфікація ресурсу Service, де вказується тип служби, селектор та порти.
  type: ClusterIP #Тип служби (ClusterIP означає, що служба доступна лише в межах кластеру).
  selector: # Селектор, за яким обираються ті Pod'и, для яких ця служба буде доступна.
    app: bookbyte 
  ports: #Порти, які служба буде відслідковувати.
  - name: bookbyte #Перший порт (80) призначений для експозиції служби "bookbyte".
    protocol: TCP #протокол (TCP)
    port: 80
    targetPort: 80
  - name: bookmgrpc #Другий порт (666) призначений для експозиції служби "bookmgrpc".
    protocol: TCP #протокол (TCP)
    port: 666
    targetPort: 666