#Даний код є описом Kubernetes-ресурсів для розгортання та сервісу контейнеризованого додатку

apiVersion: apps/v1 #Вказує версію API для об'єкта Deployment.
kind: Deployment  # визначає, як Kubernetes повинен розгортати та керувати робочими контейнерами.
metadata: #Метадані для розгортання, такі як ім'я.
  name: book-depl
spec: #Специфікація розгортання, яка включає:
  replicas: 1 #вказує, що повинен бути один екземпляр контейнера.
  selector: # визначає, за допомогою якого позначення вибирати потрібні ресурси.
    matchLabels:
      app: bookcollection
  template: # Шаблон для створення подібних контейнерів, який включає:
    metadata: #Метадані для подібних контейнерів.
      labels: #Мітки для визначення контейнера (в даному випадку, "app: bookcollection").
        app: bookcollection
    spec: #Специфікація самого контейнера, включаючи ім'я, образ та порт, на якому контейнер слухатиме.
      containers:
      - name: bookcollection # Ім'я контейнера
        image: dipas/bookcollection:latest # Docker образ для використання
        ports: #Параметри порту, який контейнер використовує (80).
        - containerPort: 80 

---
apiVersion: v1 #Версія API для об'єкту Service.
kind: Service #Тип ресурсу (Service).
metadata: #: Метадані ресурсу, включаючи унікальне ім'я (book-clusterip-srv).
  name: book-clusterip-srv
spec: #Специфікація сервісу, включаючи тип (ClusterIP), селектор для вибору реплік та визначення портів.
  type: ClusterIP #Тип сервісу (ClusterIP - сервіс з внутрішньою IP-адресою).
  selector: #Вибір реплік за допомогою міток.
    app: bookcollection
  ports: #Специфікація портів сервісу.
  - name: bookcollection  #Перший порт (80) призначений для експозиції служби "bookcollection".
    protocol: TCP
    port: 80
    targetPort: 80
  - name: bookmgrpc #Другий порт (666) призначений для експозиції служби "bookmgrpc".
    protocol: bookmgrpc
    port: 666
    targetPort: 666


//Kubernetes -- це відкрите програмне забезпечення для оркестрації контейнеризованих додатків. 
Це система, яка полегшує автоматизацію розгортання, 
масштабування та управління додатками, які упаковані у контейнери.