#Цей код є описом конфігурації Kubernetes, яка створює розгортання (Deployment)
# та два сервіси (Service) для RabbitMQ, щоб забезпечити доступ до нього в Kubernetes кластері

apiVersion: apps/v1 #Версія API для ресурсу Deployment.
kind: Deployment #Тип ресурсу
metadata: # Метадані для розгортання, включаючи його ім'я.
  name: rabbitmq-depl
spec: #Специфікація розгортання, включаючи кількість реплік (replicas) та шаблон (template) для створення подів.
  replicas: 1 #Означає, що має бути одна репліка контейнера RabbitMQ.
  selector: #Визначає, як вибрати поди для цього розгортання за допомогою міток (labels).
    matchLabels:
      app: rabbitmq
  template: #Шаблон для створення подів.
    metadata: #Метадані для пода, включаючи його мітки.
      labels: 
        app: rabbitmq
    spec: # Специфікація контейнера.
      containers: #Список контейнерів, у цьому випадку, один контейнер для RabbitMQ.
        - name: rabbitmq # Ім'я контейнера.
          image: rabbitmq:3-management #Образ контейнера, у цьому випадку, RabbitMQ з включеним менеджментом (версія 3).
          ports: #Список портів, які повинні бути відкриті в контейнері.
            - containerPort: 15672 #Порт контейнера для керування (15672) 
              name: rbmq-mgmt-port
            - containerPort: 5672 #та обміну повідомленнями (5672).
              name: rbmq-msg-port
---
apiVersion: v1 #Версія API для ресурсу Service.
kind: Service #Тип ресурсу
metadata: # Метадані для сервісу, включаючи його ім'я.
  name: rabbitmq-clusterip-srv
spec: #Специфікація сервісу.
  type: ClusterIP #Означає, що це внутрішній сервіс з ClusterIP, доступний лише всередині Kubernetes кластеру.
  selector: #Визначає, як вибрати поди для обслуговування сервісу.
    app: rabbitmq
  ports: #Список портів, які слід відкрити для сервісу.
  - name: rbmq-mgmt-port # Ім'я порту.
    protocol: TCP #Протокол (TCP).
    port: 15672 #Порт сервісу, доступний всередині кластеру.
    targetPort: 15672 #Порт контейнера, на який повинен спрямовуватися трафік.
  - name: rbmq-msg-port # Ім'я порту.
    protocol: TCP #Протокол (TCP).
    port: 5672 #Порт сервісу, доступний всередині кластеру.
    targetPort: 5672 #Порт контейнера, на який повинен спрямовуватися трафік.
---
apiVersion: v1 #Версія API для ресурсу Service.
kind: Service #Тип ресурсу
metadata:  # Метадані для сервісу, включаючи його ім'я.
  name: rabbitmq-loadbalancer
spec: #Специфікація сервісу.
  type: LoadBalancer #Означає, що це внутрішній сервіс , доступний лише всередині Kubernetes кластеру.
  selector: #Визначає, як вибрати поди для обслуговування сервісу.
    app: rabbitmq
  ports: #Список портів, які слід відкрити для сервісу.
  - name: rbmq-mgmt-port  # Ім'я порту.
    protocol: TCP #Протокол (TCP).
    port: 15672 #Порт сервісу, доступний всередині кластеру.
    targetPort: 15672 #Порт контейнера, на який повинен спрямовуватися трафік.
  - name: rbmq-msg-port # Ім'я порту.
    protocol: TCP #Протокол (TCP).
    port: 5672 #Порт сервісу, доступний всередині кластеру.
    targetPort: 5672 #Порт контейнера, на який повинен спрямовуватися трафік.